# Token Metrics AI API SDK - Example Usage

This notebook demonstrates how to use the Token Metrics AI API Python SDK to access cryptocurrency data, trading signals, market metrics, and AI-powered insights.

## Setup

First, install the SDK if you haven't already:

In [ ]:
# Uncomment to install
# !pip install tmai-api

Import the SDK and initialize the client:

In [1]:
from tmai_api import TokenMetricsClient
import pandas as pd
import matplotlib.pyplot as plt

# Initialize with your API key
client = TokenMetricsClient(api_key="tm-b7212f8d-1bcb-4c40-be3f-b4d1a4eeee72")

## Example 1: Get Token Information

Let's retrieve information about specific tokens:

In [ ]:
# Get information for Bitcoin and Ethereum
tokens = client.tokens.get(symbol="BTC,ETH")
print(f"Found {len(tokens.get('data', []))} tokens")

# Convert to DataFrame for easier exploration
tokens_df = client.tokens.get_dataframe(symbol="BTC,ETH")
tokens_df.head()

## Example 2: Get Hourly OHLCV Data

Get price and volume data for the last 7 days:

In [ ]:
from datetime import datetime, timedelta

# Calculate dates for last 60 days (to demonstrate automatic date chunking)
end_date = datetime.now().strftime("%Y-%m-%d")
start_date = (datetime.now() - timedelta(days=29)).strftime("%Y-%m-%d")

# Get OHLCV data - the SDK will automatically handle the 29-day limit and show a progress bar
ohlcv_df = client.hourly_ohlcv.get_dataframe(
    symbol="BTC", 
    startDate=start_date,
    endDate=end_date
)

# Display the most recent data
ohlcv_df.head()

## Example 3: Get Daily OHLCV Data

Get daily price and volume data for the last 30 days:

In [7]:
from datetime import datetime, timedelta

# Calculate dates for last 90 days (demonstrating the automatic date chunking)
end_date = datetime.now().strftime("%Y-%m-%d")
start_date = (datetime.now() - timedelta(days=190)).strftime("%Y-%m-%d")

# Get daily OHLCV data with automatic chunking and pagination
# The SDK will automatically handle the 29-day limit and show a progress bar
daily_ohlcv_df = client.daily_ohlcv.get_dataframe(
    symbol="BTC",
    startDate=start_date,
    endDate=end_date
)

# Display the most recent data
daily_ohlcv_df

Fetching daily-ohlcv data: 100%|██████████| 7/7 [00:06<00:00,  1.10chunk/s]

,TOKEN_ID,TOKEN_NAME,TOKEN_SYMBOL,DATE,OPEN,HIGH,LOW,CLOSE,VOLUME
0,35621,batcat,BTC,2024-10-18T00:00:00.000Z,0.000399,0.000399,0.000395,0.000398,4.415917e+04
1,3375,Bitcoin,BTC,2024-10-18T00:00:00.000Z,67381.000000,68970.000000,67164.000000,68216.000000,3.608203e+10
2,3375,Bitcoin,BTC,2024-10-17T00:00:00.000Z,67621.000000,67928.000000,66767.000000,67440.000000,3.488044e+10
3,33649,BlackrockTradingCurrency,BTC,2024-10-17T00:00:00.000Z,0.029601,0.029601,0.029492,0.029492,0.000000e+00
4,39218,Osmosis allBTC,BTC,2024-10-17T00:00:00.000Z,67596.000000,67753.000000,66747.000000,66905.000000,8.390969e+05
...,...,...,...,...,...,...,...,...,...
545,3375,Bitcoin,BTC,2025-03-13T00:00:00.000Z,83440.000000,83884.000000,83440.000000,83884.000000,4.178219e+10
546,35621,batcat,BTC,2025-03-13T00:00:00.000Z,0.000030,0.000030,0.000030,0.000030,2.259097e+03
547,3375,Bitcoin,BTC,2025-03-12T00:00:00.000Z,82586.000000,82898.000000,82586.000000,82799.000000,5.640446e+10
548,39218,Osmosis allBTC,BTC,2025-03-12T00:00:00.000Z,82130.000000,82517.000000,82130.000000,82349.000000,3.908453e+06
549,35621,batcat,BTC,2025-03-12T00:00:00.000Z,0.000041,0.000041,0.000040,0.000040,7.235331e+02

## Example 4: Trader Grades

In [2]:
from datetime import datetime, timedelta

# Calculate dates for last 180 days (to demonstrate multiple date chunks)
end_date = datetime.now().strftime("%Y-%m-%d")
start_date = (datetime.now() - timedelta(days=180)).strftime("%Y-%m-%d")

# Get trader grades - the SDK will automatically handle date chunking and show a progress bar
trader_grades_df = client.trader_grades.get_dataframe(
    symbol="BTC,ETH,SOL,BNB,XRP",
    startDate=start_date,
    endDate=end_date
)

# Display the most recent grades
trader_grades_df

Fetching trader-grades data: 100%|██████████| 7/7 [00:05<00:00,  1.37chunk/s]

,TOKEN_ID,TOKEN_NAME,TOKEN_SYMBOL,DATE,TA_GRADE,QUANT_GRADE,TM_TRADER_GRADE,TM_TRADER_GRADE_24H_PCT_CHANGE
0,3306,Ethereum,ETH,2024-10-28T00:00:00.000Z,79.31,44.32,72.31,29.01
1,31211,Bridged Ether (StarkGate),ETH,2024-10-28T00:00:00.000Z,54.90,64.05,56.73,-5.45
2,3312,BNB,BNB,2024-10-28T00:00:00.000Z,83.33,60.74,78.81,0.32
3,3375,Bitcoin,BTC,2024-10-28T00:00:00.000Z,96.11,51.62,87.21,0.11
4,3369,XRP,XRP,2024-10-28T00:00:00.000Z,14.07,40.05,19.27,0.06
...,...,...,...,...,...,...,...,...
2144,3375,Bitcoin,BTC,2025-03-22T00:00:00.000Z,37.66,60.86,42.30,-0.01
2145,3369,XRP,XRP,2025-03-22T00:00:00.000Z,58.85,61.77,59.44,35.13
2146,40413,The Ticker Is ETH,ETH,2025-03-22T00:00:00.000Z,9.13,36.78,14.66,-1.20
2147,3306,Ethereum,ETH,2025-03-22T00:00:00.000Z,37.58,55.81,41.23,-0.06
2148,39218,Osmosis allBTC,BTC,2025-03-22T00:00:00.000Z,21.94,69.16,31.39,0.06

## Example 4: Investor Grades

Let's get the long-term investment grades:

In [3]:
# Get investor grades for the same tokens
investor_grades_df = client.investor_grades.get_dataframe(
    symbol="BTC, ETH",
    startDate=start_date,
    endDate=end_date
)

investor_grades_df.head()

Fetching investor-grades data: 100%|██████████| 7/7 [00:17<00:00,  2.48s/chunk]

,TOKEN_ID,TOKEN_NAME,TOKEN_SYMBOL,DATE,TM_INVESTOR_GRADE,TM_INVESTOR_GRADE_7D_PCT_CHANGE,FUNDAMENTAL_GRADE,TECHNOLOGY_GRADE,VALUATION_GRADE,DEFI_USAGE_SCORE,COMMUNITY_SCORE,EXCHANGE_SCORE,VC_SCORE,TOKENOMICS_SCORE,DEFI_SCANNER_SCORE,ACTIVITY_SCORE,SECURITY_SCORE,REPOSITORY_SCORE,COLLABORATION_SCORE
0,3375,Bitcoin,BTC,2024-10-25T00:00:00.000Z,61.88,0.77,NaN,NaN,NaN,10.00,8.574076,10.0,None,7.333333,NaN,NaN,None,NaN,NaN
1,3306,Ethereum,ETH,2024-10-25T00:00:00.000Z,63.13,-1.39,NaN,NaN,NaN,8.33,8.146681,10.0,None,6.000000,NaN,NaN,None,NaN,NaN
2,3306,Ethereum,ETH,2024-10-24T00:00:00.000Z,63.13,-1.39,NaN,NaN,NaN,8.33,8.146681,10.0,None,6.000000,NaN,NaN,None,NaN,NaN
3,3375,Bitcoin,BTC,2024-10-24T00:00:00.000Z,61.88,0.77,NaN,NaN,NaN,10.00,8.574076,10.0,None,7.333333,NaN,NaN,None,NaN,NaN
4,3375,Bitcoin,BTC,2024-10-23T00:00:00.000Z,61.88,0.77,NaN,NaN,NaN,10.00,8.574076,10.0,None,7.333333,NaN,NaN,None,NaN,NaN

## Example 5: Market Metrics

Get overall market sentiment data:

In [4]:
# Get market metrics
market_metrics_df = client.market_metrics.get_dataframe(
    startDate=start_date,
    endDate=end_date
)

market_metrics_df.head()

Fetching market-metrics data: 100%|██████████| 7/7 [00:02<00:00,  2.76chunk/s]

,DATE,TOTAL_CRYPTO_MCAP,TM_GRADE_PERC_HIGH_COINS,TM_GRADE_SIGNAL,LAST_TM_GRADE_SIGNAL
0,2024-10-28T00:00:00.000Z,2.404974e+12,32.666667,0,-1
1,2024-10-27T00:00:00.000Z,2.380913e+12,30.666667,0,-1
2,2024-10-26T00:00:00.000Z,2.366574e+12,24.333333,-1,-1
3,2024-10-25T00:00:00.000Z,2.431707e+12,37.000000,0,1
4,2024-10-24T00:00:00.000Z,2.420817e+12,42.000000,0,1

## Example 6: Trader Indices

Get the AI-generated trading portfolios:

In [ ]:
# Get trader indices
trader_indices_df = client.trader_indices.get_dataframe(
    startDate=start_date,
    endDate=end_date
)

trader_indices_df.head()

## Example 7: AI Agent (Chatbot)

Let's interact with the Token Metrics AI chatbot:

In [ ]:
# Ask a simple question
question = "What is the next 100x coin?"
response = client.ai_agent.ask(question)

# Print the full response
import json
print(json.dumps(response, indent=2))

# Get just the answer text
answer = client.ai_agent.get_answer_text(question)
print(f"\nAI says: {answer}")

## Example 8: AI Reports

Get the latest AI-generated trading and investment reports:

In [ ]:
# Get AI reports for Bitcoin and Ethereum
ai_reports = client.ai_reports.get(symbol="BTC,ETH")
print(f"Found {len(ai_reports.get('data', []))} reports")

# Convert to DataFrame
ai_reports_df = client.ai_reports.get_dataframe(symbol="BTC,ETH")
ai_reports_df.head()

## Example 9: Trading Signals

Get the AI-generated trading signals for long and short positions:

In [ ]:
# Get trading signals for Bitcoin and Ethereum
trading_signals = client.trading_signals.get(
    symbol="BTC,ETH",
    startDate=start_date,
    endDate=end_date,
    signal="1"  # Bullish signals
)

# Convert to DataFrame
trading_signals_df = client.trading_signals.get_dataframe(
    symbol="BTC,ETH",
    startDate=start_date,
    endDate=end_date,
    signal="1"  # Bullish signals
)

trading_signals_df.head()

## Conclusion

This notebook demonstrated how to use the Token Metrics AI API SDK to access various cryptocurrency data, metrics, and AI-powered tools. You can use this data for trading signal generation, portfolio optimization, or market analysis.

For more information, refer to the [official documentation](https://api.tokenmetrics.com/docs).