# Token Metrics AI API SDK - Example Usage

This notebook demonstrates how to use the Token Metrics AI API Python SDK to access cryptocurrency data, trading signals, market metrics, and AI-powered insights.

## Setup

First, install the SDK if you haven't already:

In [ ]:
# Uncomment to install
# !pip install tmai-api

Import the SDK and initialize the client:

In [2]:
from tmai_api import TokenMetricsClient
import pandas as pd
import matplotlib.pyplot as plt

# Initialize with your API key
client = TokenMetricsClient(api_key="YOUR-API-KEY")

## Example 1: Get Token Information

Let's retrieve information about specific tokens:

In [3]:
# Get information for Bitcoin and Ethereum
tokens = client.tokens.get(symbol="BTC,ETH")
print(f"Found {len(tokens.get('data', []))} tokens")

# Convert to DataFrame for easier exploration
tokens_df = client.tokens.get_dataframe(symbol="BTC,ETH")
tokens_df.head()

Found 18 tokens

,TOKEN_ID,TOKEN_NAME,TOKEN_SYMBOL,EXCHANGE_LIST,CATEGORY_LIST,tm_link,contract_address,TM_LINK
0,31211,Bridged Ether (StarkGate),ETH,"[{'exchange_id': 'nostra', 'exchange_name': 'N...","[{'category_id': 276, 'category_name': 'Starkn...",bridged-wrapped-ether-starkgate,{'starknet': '0x49d36570d4e46f48e99674bd3fcc84...,https://app.tokenmetrics.com/undefined
1,31615,Bridged Binance-Peg Ethereum (opBNB),ETH,"[{'exchange_id': 'pancakeswap-v3-opbnb', 'exch...","[{'category_id': 599, 'category_name': 'opBNB ...",bridged-binance-peg-ethereum-opbnb,{'opbnb': '0xe7798f023fc62146e8aa1b36da45fb708...,https://app.tokenmetrics.com/undefined
2,33534,The Infinite Garden,ETH,"[{'exchange_id': 'uniswap_v2', 'exchange_name'...","[{'category_id': 143, 'category_name': 'Ethere...",the-infinite-garden,{'ethereum': '0x5e21d1ee5cf0077b314c381720273a...,https://app.tokenmetrics.com/undefined
3,33649,BlackrockTradingCurrency,BTC,"[{'exchange_id': 'uniswap_v2', 'exchange_name'...","[{'category_id': 89, 'category_name': 'Decentr...",blackrocktradingcurrency,{'ethereum': '0xbd6323a83b613f668687014e8a5852...,https://app.tokenmetrics.com/undefined
4,40225,Meld Bridged BTC (Meld),BTC,None,"[{'category_id': 573, 'category_name': 'Bridge...",meld-bridged-btc-meld,{'meld': '0x333008cfcbfbefffbb546abf237adc4061...,https://app.tokenmetrics.com/undefined

## Example 2: Get Hourly OHLCV Data

Get price and volume data for the last 7 days:

In [4]:
from datetime import datetime, timedelta

# Calculate dates for last 7 days
end_date = datetime.now().strftime("%Y-%m-%d")
start_date = (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d")

# Get OHLCV data
ohlcv_data = client.hourly_ohlcv.get(
    symbol="BTC",
    startDate=start_date,
    endDate=end_date
)

# Convert to DataFrame
ohlcv_df = client.hourly_ohlcv.get_dataframe(
    symbol="BTC",
    startDate=start_date,
    endDate=end_date
)

# Display the most recent data
ohlcv_df.head()

,TOKEN_ID,TOKEN_NAME,TOKEN_SYMBOL,TIMESTAMP,OPEN,HIGH,LOW,CLOSE,VOLUME
0,35621,batcat,BTC,2025-03-25T23:25:22.064Z,0.000034,0.000034,0.000034,0.000034,4.464748e+02
1,3375,Bitcoin,BTC,2025-03-25T23:25:22.064Z,87448.000000,87651.000000,87398.000000,87651.000000,3.014219e+10
2,39218,Osmosis allBTC,BTC,2025-03-25T23:25:22.064Z,87298.000000,87298.000000,87166.000000,87293.000000,3.032165e+06
3,35621,batcat,BTC,2025-03-25T22:25:25.899Z,0.000035,0.000035,0.000034,0.000035,4.508780e+02
4,39218,Osmosis allBTC,BTC,2025-03-25T22:25:25.899Z,87881.000000,87881.000000,87688.000000,87828.000000,3.056436e+06

## Example 3: Get Trader Grades

Let's get the short-term trading grades for various tokens:

In [6]:
# Get trader grades for top coins
trader_grades = client.trader_grades.get(
    symbol="BTC,ETH,SOL,BNB,XRP",
    startDate=start_date,
    endDate=end_date
)

# Convert to DataFrame
trader_grades_df = client.trader_grades.get_dataframe(
    symbol="BTC,ETH,SOL,BNB,XRP",
    startDate=start_date,
    endDate=end_date
)

trader_grades_df.head()

,TOKEN_ID,TOKEN_NAME,TOKEN_SYMBOL,DATE,TA_GRADE,QUANT_GRADE,TM_TRADER_GRADE,TM_TRADER_GRADE_24H_PCT_CHANGE
0,3375,Bitcoin,BTC,2025-03-26T00:00:00.000Z,81.90,60.81,77.68,-0.36
1,3306,Ethereum,ETH,2025-03-26T00:00:00.000Z,37.60,55.75,41.23,-0.03
2,35621,batcat,BTC,2025-03-26T00:00:00.000Z,29.63,40.61,31.83,11.73
3,39220,Osmosis allETH,ETH,2025-03-26T00:00:00.000Z,37.60,45.65,39.21,-0.10
4,30244,HarryPotterObamaPacMan8Inu,XRP,2025-03-26T00:00:00.000Z,81.90,44.76,74.47,-0.36

## Example 4: Investor Grades

Let's get the long-term investment grades:

In [10]:
# Get investor grades for the same tokens
investor_grades_df = client.investor_grades.get_dataframe(
    symbol="BTC, ETH",
    startDate=start_date,
    endDate=end_date
)

investor_grades_df.head()

,TOKEN_ID,TOKEN_NAME,TOKEN_SYMBOL,DATE,TM_INVESTOR_GRADE,TM_INVESTOR_GRADE_7D_PCT_CHANGE,FUNDAMENTAL_GRADE,TECHNOLOGY_GRADE,VALUATION_GRADE,DEFI_USAGE_SCORE,COMMUNITY_SCORE,EXCHANGE_SCORE,VC_SCORE,TOKENOMICS_SCORE,DEFI_SCANNER_SCORE,ACTIVITY_SCORE,SECURITY_SCORE,REPOSITORY_SCORE,COLLABORATION_SCORE
0,41627,Bridged Wrapped Ether (Eclipse),ETH,2025-03-26T00:00:00.000Z,50.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,NaN
1,3306,Ethereum,ETH,2025-03-26T00:00:00.000Z,62.88,4.64,82.3,93.49,8.0,9.17,8.271481,10.0,None,6.000000,10.0,9.66,None,7.2,10.0
2,3375,Bitcoin,BTC,2025-03-26T00:00:00.000Z,58.94,-1.64,84.1,78.42,8.0,8.33,8.322292,10.0,None,7.333333,NaN,8.73,None,7.9,6.6
3,21994,Ethereum (Wormhole),ETH,2025-03-26T00:00:00.000Z,50.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,NaN
4,31211,Bridged Ether (StarkGate),ETH,2025-03-26T00:00:00.000Z,50.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,None,NaN,NaN

## Example 5: Market Metrics

Get overall market sentiment data:

In [ ]:
# Get market metrics
market_metrics_df = client.market_metrics.get_dataframe(
    startDate=start_date,
    endDate=end_date
)

market_metrics_df.head()

## Example 6: Trader Indices

Get the AI-generated trading portfolios:

In [11]:
# Get trader indices
trader_indices_df = client.trader_indices.get_dataframe(
    startDate=start_date,
    endDate=end_date
)

trader_indices_df.head()

,PORTFOLIO_DATE,TOKEN_ID,TOKEN_NAME,TOKEN_SYMBOL,INDEX_WEIGHT,INITIAL_PRICE,AMOUNT_OF_TOKENS
0,2025-03-26,41628,BugsCoin,BGSC,0.054748,0.008533,6.415902e+04
1,2025-03-26,32137,Fimarkcoin.com,FMC,0.051283,0.002115,2.424322e+05
2,2025-03-26,29421,Cheems Token,CHEEMS,0.057103,0.000002,2.812953e+08
3,2025-03-26,36706,Ekubo Protocol,EKUBO,0.269152,7.050000,3.817761e+02
4,2025-03-26,42646,Plume,PLUME,0.036185,0.193012,1.874778e+03

## Example 7: AI Agent (Chatbot)

Let's interact with the Token Metrics AI chatbot:

In [12]:
# Ask a simple question
question = "What is the next 100x coin?"
response = client.ai_agent.ask(question)

# Print the full response
import json
print(json.dumps(response, indent=2))

# Get just the answer text
answer = client.ai_agent.get_answer_text(question)
print(f"\nAI says: {answer}")

{
  "success": true,
  "message": "AI Chatbot response successful",
  "answer": "Predicting the next 100x coin is speculative, but here are some contenders based on current trends and potential: Polygon is making waves with its expanding Web3 adoption and strategic partnerships with giants like Disney and Nike. Arbitrum is gaining traction in DeFi, addressing Ethereum's congestion issues, and collaborating with major DeFi protocols. Thorchain is poised to lead in blockchain interoperability, crucial for the growing demand for cross-chain trading. Gala Games is tapping into the Web3 gaming boom, with a strong foothold in the NFT and play-to-earn markets. Always do your own research and consider the risks before investing!",
  "thread": [
    {
      "user": "What is the next 100x coin?"
    },
    {
      "chatbot": "Predicting the next 100x coin is speculative, but here are some contenders based on current trends and potential: Polygon is making waves with its expanding Web3 adoption and strategic partnerships with giants like Disney and Nike. Arbitrum is gaining traction in DeFi, addressing Ethereum's congestion issues, and collaborating with major DeFi protocols. Thorchain is poised to lead in blockchain interoperability, crucial for the growing demand for cross-chain trading. Gala Games is tapping into the Web3 gaming boom, with a strong foothold in the NFT and play-to-earn markets. Always do your own research and consider the risks before investing!"
    }
  ]
}

AI says: Predicting the next 100x coin is highly speculative, but here are some intriguing contenders: Pepe Unchained leverages Ethereum Layer-2 for low-fee staking and has strong community support, aligning with the meme coin trend. Dawgz AI combines meme culture with AI solutions, featuring a deflationary model and active community engagement. Thorchain offers cross-chain liquidity, tapping into the growing demand for interoperability. Arbitrum addresses Ethereum's scalability issues with fast transactions and strong developer activity. Gala Games is expanding in the NFT gaming space, with popular titles boosting its ecosystem. Always do your own research and consider the risks before investing!

## Example 8: AI Reports

Get the latest AI-generated trading and investment reports:

In [13]:
# Get AI reports for Bitcoin and Ethereum
ai_reports = client.ai_reports.get(symbol="BTC,ETH")
print(f"Found {len(ai_reports.get('data', []))} reports")

# Convert to DataFrame
ai_reports_df = client.ai_reports.get_dataframe(symbol="BTC,ETH")
ai_reports_df.head()

Found 2 reports

,TOKEN_ID,TOKEN_NAME,SYMBOL,TRADER_REPORT,FUNDAMENTAL_REPORT,TECHNOLOGY_REPORT
0,3306,Ethereum,ETH,"## Introduction\n\nIn this report, we will ana...","## Introduction\n\nEthereum, known for its sma...",## Development Activity\n- **Total Commits for...
1,3375,Bitcoin,BTC,"## Introduction\n\nIn this report, we will ana...",## Introduction\n\nBitcoin is the pioneer cryp...,## Development Activity\n\n - Total Commits f...

## Example 9: Trading Signals

Get the AI-generated trading signals for long and short positions:

In [14]:
# Get trading signals for Bitcoin and Ethereum
trading_signals = client.trading_signals.get(
    symbol="BTC,ETH",
    startDate=start_date,
    endDate=end_date,
    signal="1"  # Bullish signals
)

# Convert to DataFrame
trading_signals_df = client.trading_signals.get_dataframe(
    symbol="BTC,ETH",
    startDate=start_date,
    endDate=end_date,
    signal="1"  # Bullish signals
)

trading_signals_df.head()

,TOKEN_ID,TOKEN_NAME,TOKEN_SYMBOL,DATE,TRADING_SIGNAL,TOKEN_TREND,TRADING_SIGNALS_RETURNS,HOLDING_RETURNS,tm_link,TM_TRADER_GRADE,TM_INVESTOR_GRADE,TM_LINK
0,3375,Bitcoin,BTC,2025-03-26T00:00:00.000Z,1,1,47639.7508,7997.8991,bitcoin,77.68,58.94,https://app.tokenmetrics.com/undefined
1,39218,Osmosis allBTC,BTC,2025-03-26T00:00:00.000Z,1,1,-0.0142,0.4980,osmosis-allbtc,79.45,50.00,https://app.tokenmetrics.com/undefined
2,3375,Bitcoin,BTC,2025-03-25T00:00:00.000Z,1,1,47639.7508,7997.8991,bitcoin,77.68,58.94,https://app.tokenmetrics.com/undefined
3,39218,Osmosis allBTC,BTC,2025-03-25T00:00:00.000Z,1,1,-0.0142,0.4980,osmosis-allbtc,79.45,50.00,https://app.tokenmetrics.com/undefined

## Conclusion

This notebook demonstrated how to use the Token Metrics AI API SDK to access various cryptocurrency data, metrics, and AI-powered tools. You can use this data for trading signal generation, portfolio optimization, or market analysis.

For more information, refer to the [official documentation](https://api.tokenmetrics.com/docs).